services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app"  # Use backend.app:app instead of app:app
    plan: free
