services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.app:app"  # Adjust this if your app is located elsewhere
    plan: free
